name: Auto update

on:
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get install openssh-client python3-setuptools

      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6
        with:
          repository: JinnLynn/genpac
          path: genpac

      - uses: actions/checkout@v6
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - uses: petronny/git-config-user@master
        with:
          path: .

      - run: |
          cd genpac
          # sed 's/from collections import Callable/from collections.abc import Callable/g' -i $(grep 'from collections import Callable' . -rIl)
          sudo pip3 install .

      - name: Update
        run: |
          set -x

          
          pac_proxy=""
          if [ "${{ secrets.SOCKS_PROXY }}" != '' ]; then 
            pac_proxy="SOCKS5 ${{ secrets.SOCKS_PROXY }};"
          fi
          if [ "${{ secrets.HTTP_PROXY}}" != '' ];then
            pac_proxy=${pac_proxy}"HTTP ${{ secrets.HTTP_PROXY}};"
          fi
          pac_proxy=${pac_proxy}"DIRECT"
          genpac --format=pac --pac-proxy="${pac_proxy}" --gfwlist-url - --gfwlist-local $(pwd)/gfwlist/gfwlist.txt -o gfwlist.pac
          sed '1,7d' -i gfwlist.pac

          git add gfwlist.pac
          git commit -m "[$(LANG=C date)] auto update" || exit 0

          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0

          git push origin master
